# Generated by Django 3.2.9 on 2023-01-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20230111_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='rate',
        ),
    ]
