# Generated by Django 3.2.9 on 2023-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movie_directors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directors',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Actor'),
        ),
    ]
