# Generated by Django 3.2.9 on 2023-01-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20230116_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.comment'),
        ),
    ]
